### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by hktalent** [ym2011/ScanBackdoor#1]
环境：Python 2.7.10
mac os 10.11.6

python scan.py -l -p http://....../
Traceback (most recent call last):
  File "scan.py", line 10, in <module>
    import core 
  File "/Volumes/BOOK/安全/project/ym2011_ScanBackdoor/core.py", line 37
    if **name** == '**main**':
     ^
IndentationError: expected an indented block

**Comment by Michael-Scofields** [comment]
代码都没写完~~
